- platform: tautulli
  api_key: !secret tautulli_apikey
  host: !secret media_host
  port: !secret tautulli_port
- platform: template
  sensors:
    distance_to_david:
      unit_of_measurement: mi
      friendly_name: "Distance to David"
      value_template: "{{(distance('person.scott_jeffers', 'person.david_jeffers')) | round(2)}}" 
      attribute_templates:
          name: "David"
          gmapsid: "104319806339731336469"
          location: "{{ states('person.david_jeffers') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.david_jeffers','gps_accuracy') }}"
          source: "{{ state_attr('person.david_jeffers','source') }}"
          entity_picture: "{{ state_attr('person.david_jeffers','entity_picture') }}"
    distance_to_nicole:
      unit_of_measurement: mi
      friendly_name: "Distance to Nicole"
      value_template: "{{(distance('person.scott_jeffers', 'person.nicole_derozier')) | round(2)}}" 
      attribute_templates:
          name: "Nicole"
          gmapsid: "104689387514719813163"
          location: " {{ states('person.nicole_derozier') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.nicole_derozier','gps_accuracy') }}"
          source: "{{ state_attr('person.nicole_derozier','source') }}"
          entity_picture: "{{ state_attr('person.nicole_derozier','entity_picture') }}"
    distance_to_crystal:
      unit_of_measurement: mi
      friendly_name: "Distance to Crystal"
      value_template: "{{(distance('person.scott_jeffers', 'person.crystal_dunham')) | round(2)}}" 
      attribute_templates:
          name: "Crystal"
          gmapsid: "109263310129727948968"
          location: " {{ states('person.crystal_dunham') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.crystal_dunham','gps_accuracy') }}"
          source: "{{ state_attr('person.crystal_dunham','source') }}"
          entity_picture: "{{ state_attr('person.crystal_dunham','entity_picture') }}"
    distance_to_theo:
      unit_of_measurement: mi
      friendly_name: "Distance to Theo"
      value_template: "{{(distance('person.scott_jeffers', 'person.theo_zografos')) | round(2)}}" 
      attribute_templates:
          name: "Theo"
          gmapsid: "117596500104838591962"
          location: " {{ states('person.theo_zografos') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.theo_zografos','gps_accuracy') }}"
          source: "{{ state_attr('person.theo_zografos','source') }}"
          entity_picture: "{{ state_attr('person.theo_zografos','entity_picture') }}"
    distance_to_mark:
      unit_of_measurement: mi
      friendly_name: "Distance to Mark"
      value_template: "{{(distance('person.scott_jeffers', 'person.mark_murphy')) | round(2)}}" 
      attribute_templates:
          name: "Mark"
          gmapsid: "111987102632865601915"
          location: " {{ states('person.mark_murphy') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.mark_murphy','gps_accuracy') }}"
          source: "{{ state_attr('person.mark_murphy','source') }}"
          entity_picture: "{{ state_attr('person.mark_murphy','entity_picture') }}"
    distance_to_haley_gainey:
      unit_of_measurement: mi
      friendly_name: "Distance to Haley"
      value_template: "{{(distance('person.scott_jeffers', 'person.haley_gainey')) | round(2)}}" 
      attribute_templates:
          name: "Haley"
          gmapsid: "105415064359769958074"
          location: " {{ states('person.haley_gainey') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.haley_gainey','gps_accuracy') }}"
          source: "{{ state_attr('person.haley_gainey','source') }}"
          entity_picture: "{{ state_attr('person.haley_gainey','entity_picture') }}"
    distance_to_rick:
      unit_of_measurement: mi
      friendly_name: "Distance to Rick"
      value_template: "{{(distance('person.scott_jeffers', 'person.rick_manship')) | round(2)}}" 
      attribute_templates:
          name: "Rick"
          gmapsid: "112116801067791073109"
          location: " {{ states('person.rick_manship') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.rick_manship','gps_accuracy') }}"
          source: "{{ state_attr('person.rick_manship','source') }}"
          entity_picture: "{{ state_attr('person.rick_manship','entity_picture') }}"
    distance_to_trailer:
      unit_of_measurement: mi
      friendly_name: "Distance to Trailer"
      value_template: "{{(distance('person.scott_jeffers', 'person.trailer')) | round(2)}}" 
      attribute_templates:
          name: "Trailer"
          gmapsid: "unknown"
          location: " {{ states('person.trailer') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.trailer','gps_accuracy') }}"
          source: "{{ state_attr('person.trailer','source') }}"
          entity_picture: "{{ state_attr('person.trailer','entity_picture') }}"
    distance_to_scott_jolly:
      unit_of_measurement: mi
      friendly_name: "Distance to Jolly"
      value_template: "{{(distance('person.scott_jeffers', 'person.scott_jolley')) | round(2)}}" 
      attribute_templates:
          name: "Scott Jolly"
          gmapsid: "100595253634384490622"
          location: " {{ states('person.scott_jolley') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.scott_jolley','gps_accuracy') }}"
          source: "{{ state_attr('person.scott_jolley','source') }}"
          entity_picture: "{{ state_attr('person.scott_jolley','entity_picture') }}"
    distance_to_tawaha:
      unit_of_measurement: mi
      friendly_name: "Distance to Tawaha"
      value_template: "{{(distance('person.scott_jeffers', 'person.tawaha_swihart')) | round(2)}}" 
      attribute_templates:
          name: "Tawaha"
          gmapsid: "114590642674688311408"
          location: " {{ states('person.tawaha_swihart') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.tawaha_swihart','gps_accuracy') }}"
          source: "{{ state_attr('person.tawaha_swihart','source') }}"
          entity_picture: "{{ state_attr('person.tawaha_swihart','entity_picture') }}"
    distance_to_sauaiwa:
      unit_of_measurement: mi
      friendly_name: "Distance to Sauaiwa"
      value_template: "{{(distance('person.scott_jeffers', 'person.sauaiwa_swihart')) | round(2)}}" 
      attribute_templates:
          name: "Sauaiwa"
          gmapsid: "111919563340176050827"
          location: " {{ states('person.sauaiwa_swihart') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.sauaiwa_swihart','gps_accuracy') }}"
          source: "{{ state_attr('person.sauaiwa_swihart','source') }}"
          entity_picture: "{{ state_attr('person.sauaiwa_swihart','entity_picture') }}"
    distance_to_terri:
      unit_of_measurement: mi
      friendly_name: "Distance to Terri"
      value_template: "{{(distance('person.scott_jeffers', 'person.terri_wooten')) | round(2)}}" 
      attribute_templates:
          name: "Terri"
          gmapsid: "104193570598412200760"
          location: " {{ states('person.terri_wooten') }}"
          longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          gps_accuracy: "{{ state_attr('person.terri_wooten','gps_accuracy') }}"
          source: "{{ state_attr('person.terri_wooten','source') }}"
          entity_picture: "{{ state_attr('person.terri_wooten','entity_picture') }}"
    distance_mark_to_haley:
      unit_of_measurement: mi
      friendly_name: "Mark's Distance to Haley"
      value_template: "{{(distance('person.mark_murphy', 'person.haley_gainey')) | round(2)}}" 
      attribute_templates:
          haley_location: " {{ states('person.haley_gainey') }}"
          haley_longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          haley_latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          haley_gps_accuracy: "{{ state_attr('person.haley_gainey','gps_accuracy') }}"
          haley_source: "{{ state_attr('person.haley_gainey','source') }}"
          haley_gmapsid: "105415064359769958074"
          mark_location: " {{ states('person.mark_murphy') }}"
          mark_longitude: "{{ state_attr('person.david_jeffers','longitude') }}"
          mark_latitude: "{{ state_attr('person.david_jeffers','latitude') }}"
          mark_gps_accuracy: "{{ state_attr('person.mark_murphy','gps_accuracy') }}"
          mark_source: "{{ state_attr('person.mark_murphy','source') }}"
          mark_gmapsid: "111987102632865601915"