- platform: mqtt
  name: "Desk Monitor 1"
  state_topic: "stat/desk_monitors/RESULT" 
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/desk_monitors/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/desk_monitors/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Desk Monitor 2"
  state_topic: "stat/desk_monitors/RESULT" 
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "cmnd/desk_monitors/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/desk_monitors/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false