#########################################################################
#                                                                       #
#                               Humidity                                #
#                                                                       #
#########################################################################

# If Bathroom humidity is above 70% turn bathroom vent on for 10 minutes. Long term goal is to have this automation linked to an input number, where users can specify the humidity level that triggers the automation. https://www.home-assistant.io/docs/automation/trigger/#template-trigger
- id: 'bathroom_humidity_trigger_vent'
  alias: Bathroom Humidity >70%, turn on vent for 00:10:00
  trigger:
  - above: '70'
    entity_id: sensor.bathroom_4in1_relative_humidity
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: fan.bathroom_vent
    service: fan.turn_on
  - delay: 00:10:00
  - data:
      entity_id: fan.bathroom_vent
    service: fan.turn_off

# Shower humidity to trigger shower vent. Long term goal is to have this automation linked to an input number, where users can specify the humidity level that triggers the automation. https://www.home-assistant.io/docs/automation/trigger/#template-trigger
- id: 'bathroom_humidity_trigger_vent'
  alias: Bathroom Shower Humidity >70%, turn on vent for 00:10:00
  trigger:
  - above: '70'
    entity_id: sensor.shower_4in1_relative_humidity
    platform: numeric_state
  condition: []
  action:
  - alias: ''
    data:
      entity_id: fan.shower_vent
    service: fan.turn_on
  - delay: 00:10:00
  - data:
      entity_id: fan.shower_vent
    service: fan.turn_off
    
#########################################################################
#                                                                       #
#                           Bathroom Door                               #
#                                                                       #
#########################################################################

# When the bathroom door closes, turn off the bathroom fan for 10 minutes script if it's on, then turn it back on, that way anytime the bathroom door closes it can reset that script's 10 minute timer
- id: '1529290690285'
  alias: Bathroom Door Closes
  trigger:
  - entity_id: binary_sensor.bathroom_door
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: script.1529290313019 #the script that turns the bathroom vents on for 10 minutes, then turns them back off
    service: script.turn_off
  - data: {}
    service: script.1529290313019 #same script as above
  - data:
      entity_id: light.bathroom_overhead
    service: light.turn_on

# When the bathroom door opens, wait 10 seconds then turn off the light
- id: '1529291468640'
  alias: Bathroom Door Opens
  trigger:
  - entity_id: binary_sensor.bathroom_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:10
  - data:
      entity_id: light.bathroom_overhead
    service: light.turn_off
    
#########################################################################
#                                                                       #
#                         Shower Motion Sensor                          #
#                                                                       #
#########################################################################

# If there is no motion in the shower for 5 minutes, turn the shower light off.
- id: 'no_motion_in_shower'
  alias: No Motion in Shower
  trigger:
  - entity_id: sensor.shower_4in1_alarm_level
    from: '255'
    platform: state
    to: '0'
    for: 00:05:00
  condition: []
  action:
  - data:
      entity_id: light.shower
    service: light.turn_off
    
# If there is motion in the shower, lock all the doors immediatly.
- id: 'motion_in_shower_lock_doors'
  alias: Motion in Shower Locks the Door
  trigger:
  - entity_id: sensor.shower_4in1_alarm_level
    from: '0'
    platform: state
    to: '255'
  condition: []
  action:
  - service: lock.lock

# If there is motion in the shower, turn on the shower light immeditly    
- id: 'motion_in_shower_turn_on_light'
  alias: Motion in Shower Turns on the light
  trigger:
  - entity_id: sensor.shower_4in1_alarm_level
    from: '0'
    platform: state
    to: '255'
  condition: []
  action:
  - data:
      entity_id: light.shower
    service: light.turn_on
        
# Motion Auto On
- id: 'motion_in_shower_reactivate'
  alias: If Motion in the Shower Automations turn off, turn them back on
  trigger:
  - entity_id: automation.motion_in_shower
    platform: state
    to: 'off'
  condition: []
  action:
  - delay: 02:00:00
  - data:
      entity_id: 
        - automation.motion_in_shower_lock_doors
        - automation.motion_in_shower_turn_on_light
    service: automation.turn_on
