    #
    #  Automations for the Bedroom go here. 
    #

##When the closet Door opens, turn on the closet light. 
- id: 'closet_door_turns_on_light'
  alias: Closet Door Opens
  trigger:
    - entity_id: binary_sensor.bedroom_closet_door
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_closet
      
##When the closet door closes, turn off the closet light.
- id: 'closet_door_turns_off_light'
  alias: Closet Door Closes
  trigger:
    - entity_id: binary_sensor.bedroom_closet_door
      from: 'on'
      platform: state
      to: 'off'
  condition: []
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_closet

##When the bedroom door closes, turn on the bedroom lamps
- id: 'bedroom_door_turns_on_lamps'
  alias: Bedroom Door Closed
  trigger:
    - entity_id: binary_sensor.bedroom_door
      from: 'on'
      platform: state
      to: 'off'
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lamps
      

## Play a Sunrise Video From YouTube On Bedroom TV at 630 am
- id: '630am_sunrise_video_wakeup'
  initial_state: false
  alias: 6:30am Sunrise Wake-Up
  trigger:
    - at: 06:30
      platform: time
  condition: []
  action:
    - service: script.1543509679983

## Play a Sunrise Video From YouTube On Bedroom TV when at sunrise.
- id: 'sunrise_wakeup_at_sunrise'
  initial_state: false
  alias: Sunrise Wake-Up at sunrise
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
  condition: []
  action:
    - service: script.1543509679983
