    #
    #  Automations for the Bedroom go here. 
    #

    #When the closet Door opens, turn on the closet light. 
- id: 'closet_door_turns_on_light'
  alias: Closet Door Opens
  trigger:
    - entity_id: binary_sensor.bedroom_closet_door
      from: 'off'
      platform: state
      to: 'on'
  condition: []
  action:
    - data:
      entity_id: light.bedroom_closet
      service: light.turn_on

    #When the closet door closes, turn off the closet light.
 - id: 'closet_door_turns_off_light'
   alias: Closet Door Closes
   trigger:
     - entity_id: binary_sensor.bedroom_closet_door
        from: 'on'
        platform: state
        to: 'off'
   condition: []
   action:
     - data:
       entity_id: light.bedroom_closet
       service: light.turn_off

- id: 'bedroom_door_turns_on_lamps'
  alias: Bedroom Door Closed
  trigger:
    - entity_id: binary_sensor.bedroom_door
        from: 'on'
        platform: state
        to: 'off'
  condition: []
  action:
    - data:
        entity_id: light.bedroom_lamps
        service: light.turn_on

    ## Play a Sunrise Video From YouTube On Bedroom TV
- id: 'sunrise_wakeup'
  alias: Sunrise Wake-Up
  trigger:
  - at: 06:30
    platform: time
    condition: []
    action:
    - data:
      service: script.1543509679983
