#
#
#   Automations related to network devices 
# 
#
#


#                                  #
#                                  #
#         Plex Automations         #
#                                  #
#                                  #


# If the temerature gets too hot in the plex server, then turn on the external fan in the room to help mmove air around to cool it
- id: 'turn_on_the_fan_if_plex_server_is_hot'
  alias: Turn on the fan if Plex Server is hot
  trigger:
  - above: '122'
    entity_id: sensor.quexplexhtpc_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.quexplexhtpc_amd_radeon_hd_5700_series_temperatures_gpu_core
    platform: numeric_state
  - above: '140'
    entity_id: sensor.quexplexhtpc_samsung_ssd_850_evo_500gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature_2
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_st10000nm00161tt101_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: fan.kitchen_ceilingfan
    service: fan.turn_on

# If it's hot in Plex Server, post to discord channel
- alias: Hot in QuexPlex - Tell Discord
  trigger:
  - above: '122'
    entity_id: sensor.quexplexhtpc_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.quexplexhtpc_amd_radeon_hd_5700_series_temperatures_gpu_core
    platform: numeric_state
  - above: '140'
    entity_id: sensor.quexplexhtpc_samsung_ssd_850_evo_500gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature_2
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_st10000nm00161tt101_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      target: !secret discord_ha-network-devices
    service: notify.discord

# If it's hot in Plex Server, push notification to Quexser's Phone
- alias: Hot in QuexPlex - Tell Quexser
  trigger:
  - above: '122'
    entity_id: sensor.quexplexhtpc_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.quexplexhtpc_amd_radeon_hd_5700_series_temperatures_gpu_core
    platform: numeric_state
  - above: '140'
    entity_id: sensor.quexplexhtpc_samsung_ssd_850_evo_500gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature_2
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_st10000nm00161tt101_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      title: QuexPlex is Hot
    service: notify.android_pixel_xl


# If it's hot in Plex Server, push notification to Forte's Phone
- alias: Hot in QuexPlex - Tell Forte
  trigger:
  - above: '122'
    entity_id: sensor.quexplexhtpc_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.quexplexhtpc_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.quexplexhtpc_amd_radeon_hd_5700_series_temperatures_gpu_core
    platform: numeric_state
  - above: '140'
    entity_id: sensor.quexplexhtpc_samsung_ssd_850_evo_500gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_hgst_hdn728080ale604_temperatures_temperature_2
    platform: numeric_state
  - above: '120'
    entity_id: sensor.quexplexhtpc_st10000nm00161tt101_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      title: QuexPlex is Hot
    service: notify.android_rotom

#                                  #
#                                  #
#      The Beast Automations       #
#                                  #
#                                  #

# If Beast temps reach certain thresholds, post notification in discord
- id: 'hot_in_beast_tell_discord'
  alias: Hot in TheBeast - Tell Discord
  trigger:
  - above: '122'
    entity_id: sensor.thebeast_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core_2
    platform: numeric_state
  - above: '140'
    entity_id: sensor.thebeast_sandisk_ultra_ii_480gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.thebeast_wdc_wd20earx00pasb0_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      target: !secret discord_ha-network-devices
    service: notify.discord

# If Beast temps reach certain thresholds, push notification to Quexser
- id: 'hot_in_beast_tell_quexser'
  alias: Hot in TheBeast - Tell Quexser
  trigger:
  - above: '122'
    entity_id: sensor.thebeast_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core_2
    platform: numeric_state
  - above: '140'
    entity_id: sensor.thebeast_sandisk_ultra_ii_480gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.thebeast_wdc_wd20earx00pasb0_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      title: TheBeast is Hot
    service: notify.android_pixel_xl

# If Beast temps reach certain thresholds, push notification to Forte
- alias: Hot in TheBeast - Tell Forte
  trigger:
  - above: '122'
    entity_id: sensor.thebeast_amd_fx8150_temperatures_core_1__8
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_1
    platform: numeric_state
  - above: '122'
    entity_id: sensor.thebeast_asus_crosshair_v_formula_ite_it8721f_temperatures_temperature_2
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core
    platform: numeric_state
  - above: '185'
    entity_id: sensor.thebeast_radeontm_rx_460_graphics_temperatures_gpu_core_2
    platform: numeric_state
  - above: '140'
    entity_id: sensor.thebeast_sandisk_ultra_ii_480gb_temperatures_temperature
    platform: numeric_state
  - above: '120'
    entity_id: sensor.thebeast_wdc_wd20earx00pasb0_temperatures_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: It's getting hot in here! {{ states[trigger.entity_id.split(".")[0]][
        trigger.entity_id.split(".")[1]].name }} is running too hot. It just reached {{ trigger.to_state.state }} °F. 
    data:
      title: TheBeast is Hot
    service: notify.android_rotom

