#
#
# Proximity Alarms
#
#

- id: 'mark_is_close'
  alias: Mark's Proximity Alarm
  trigger:
    platform: numeric_state
    entity_id: sensor.scott_to_mark_distance
    below: 5
  action:
    service: notify.android_pixel_xl #This service is documented here: https://github.com/MCrissDev/HANotify, and is specifically targeting Quexser's Pixel
    data:
      message_type: notification
      message: Mark is less than 3 miles away!


#################################################################
#                      Unoccupied Kitchen                       #
#################################################################

- alias: No motion in the Kitchen for 30 mins, turn off the lights
  trigger: 
    - platform: state
      entity_id: sensor.kitchen_4in1_alarm_level
      from: '255' 
      to: '0'
      for: 
        hours: 0
        minutes: 30
        seconds: 0
  condition: 
    - condition: state
      entity_id: input_select.house_mode
      state: Auto
  action:
    - service: light.turn_off
      data:
        entity_id:
        - light.kitchen_overhead
        - light.kitchen_pendant
        - light.kitchen_laundryroom

#################################################################
#                     Unoccupied Bathroom                       #
#################################################################

- alias: No motion in the Bathroom for 30 mins, turn off the lights
  trigger: 
    - platform: state
      entity_id: sensor.bathroom_4in1_alarm_level
      from: '255' 
      to: '0'
      for: 
        hours: 0
        minutes: 30
        seconds: 0
  condition: 
    - condition: state
      entity_id: input_select.house_mode
      state: Auto
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bathroom_overhead
          - light.bathroom_vanity

#################################################################
#                 12-6 Nitetime Nightlight                      #
#################################################################

# Midnight - 6:00am
- id: 'kitchen_nightlight_auto'
  alias: Kitchen Nightlight Between Midnight & 6am
  trigger:
  - entity_id: sensor.kitchen_4in1_alarm_level
    from: '0'
    platform: state
    to: '255'
  condition:
  - after: 00:00
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: light.kitchen_overcabinetlighting
    service: light.turn_on
  - delay: 00:02:00
  - data:
      entity_id: light.kitchen_overcabinetlighting
    service: light.turn_off

#################################################################
#                          Welcome Lights                       #
#################################################################

- id: 'welcome_lights'
  alias: Welcome Lights
  trigger:
    platform: zone
    entity_id: device_tracker.quexpixel
    zone: zone.home
    # Event is either enter or leave
    event: enter  # or "leave"
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data:
      entity_id: light.livingroom_sofalamp
    service: light.turn_on
  - data:
      entity_id: light.bedroom_lamps
    service: light.turn_on
  - data:
      entity_id: light.outside_frontporch
    service: light.turn_on

#Automation to automatically put the house into away mode
- id: 'auto_away'
  alias: Auto Away
  trigger: []
  condition: []
  action: []

#Automation to automatically trigger the lock down script (arm home)
- id: 'auto_lock_down'
  alias: Auto Lock Down
  trigger: []
  condition: []
  action: []

#################################################################
#                          TV Backlights                        #
#################################################################

- id: 'livingroom_tv_backlight_on'
  alias: Living Room TV Backlight ON
  trigger:
  - entity_id: device_tracker.cc95d7ea7036
    platform: state
    from: not_home
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.05200381dc4f222f2120
    service: switch.turn_on

- id: 'livingroom_tv_backlight_off'
  alias: Living Room TV Backlight OFF
  trigger:
  - entity_id: device_tracker.cc95d7ea7036
    platform: state
    from: home
    to: not_home
  condition: []
  action:
  - data:
      entity_id: switch.05200381dc4f222f2120
    service: switch.turn_off

- id: 'bedroom_tv_backlight_on'
  alias: Bedroom TV Backlight ON
  trigger:
  - entity_id: device_tracker.cc95d77b0b10
    platform: state
    from: not_home
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.05200382dc4f222f6ee5
    service: switch.turn_on

- id: 'bedroom_tv_backlight_off'
  alias: Bedroom TV Backlight OFF
  trigger:
  - entity_id: device_tracker.cc95d77b0b10
    platform: state
    from: home
    to: not_home
  condition: []
  action:
  - data:
      entity_id: switch.05200382dc4f222f6ee5
    service: switch.turn_off
